
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DMEmployeeManagementService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9001/dm/employees?wsdl")
public class DMEmployeeManagementService
    extends Service
{

    private final static URL DMEMPLOYEEMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DMEMPLOYEEMANAGEMENTSERVICE_EXCEPTION;
    private final static QName DMEMPLOYEEMANAGEMENTSERVICE_QNAME = new QName("http://ws/", "DMEmployeeManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/dm/employees?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DMEMPLOYEEMANAGEMENTSERVICE_WSDL_LOCATION = url;
        DMEMPLOYEEMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public DMEmployeeManagementService() {
        super(__getWsdlLocation(), DMEMPLOYEEMANAGEMENTSERVICE_QNAME);
    }

    public DMEmployeeManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DMEMPLOYEEMANAGEMENTSERVICE_QNAME, features);
    }

    public DMEmployeeManagementService(URL wsdlLocation) {
        super(wsdlLocation, DMEMPLOYEEMANAGEMENTSERVICE_QNAME);
    }

    public DMEmployeeManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DMEMPLOYEEMANAGEMENTSERVICE_QNAME, features);
    }

    public DMEmployeeManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMEmployeeManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeManagementService
     */
    @WebEndpoint(name = "DMEmployeeManagementPort")
    public EmployeeManagementService getDMEmployeeManagementPort() {
        return super.getPort(new QName("http://ws/", "DMEmployeeManagementPort"), EmployeeManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeManagementService
     */
    @WebEndpoint(name = "DMEmployeeManagementPort")
    public EmployeeManagementService getDMEmployeeManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "DMEmployeeManagementPort"), EmployeeManagementService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DMEMPLOYEEMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw DMEMPLOYEEMANAGEMENTSERVICE_EXCEPTION;
        }
        return DMEMPLOYEEMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
