
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ws.services.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeManagementService", targetNamespace = "http://services.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManagementService {


    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://services.ws/", className = "ws.services.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://services.ws/", className = "ws.services.DeleteEmployeeResponse")
    public boolean deleteEmployee(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @param username
     * @param givenname
     * @param role
     * @param surname
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editEmployee", targetNamespace = "http://services.ws/", className = "ws.services.EditEmployee")
    @ResponseWrapper(localName = "editEmployeeResponse", targetNamespace = "http://services.ws/", className = "ws.services.EditEmployeeResponse")
    public boolean editEmployee(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "givenname", targetNamespace = "")
        String givenname,
        @WebParam(name = "surname", targetNamespace = "")
        String surname,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "role", targetNamespace = "")
        String role);

    /**
     * 
     * @param username
     * @param givenname
     * @param role
     * @param surname
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://services.ws/", className = "ws.services.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://services.ws/", className = "ws.services.AddEmployeeResponse")
    public boolean addEmployee(
        @WebParam(name = "givenname", targetNamespace = "")
        String givenname,
        @WebParam(name = "surname", targetNamespace = "")
        String surname,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "role", targetNamespace = "")
        String role);

}
